# Created by: Sergey Kozlov <kozlov.sergey.404@gmail.com>
# $FreeBSD$

PORTVERSION=	4.6.4
PKGNAMESUFFIX=	46
MASTERDIR=	${.CURDIR}/../kibana45
PKGDIR=		${.CURDIR}
DISTINFO_FILE=	${.CURDIR}/distinfo

USES=		node:6,run

.include "${MASTERDIR}/Makefile"
